In [4]:
import pandas as pd
import numpy as np
import re

In [5]:
dataset = pd.read_csv("../../data/raw/regular_season_detailed_results.csv");

In [35]:
dataset

,season,daynum,wteam,wscore,lteam,lscore,wloc,numot,wfgm,wfga,...,lfga3,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
5,2003,11,1458,81,1186,55,H,0,26,57,...,11,12,17,6,22,8,19,4,3,25
6,2003,12,1161,80,1236,62,H,0,23,55,...,15,20,28,9,21,11,30,10,4,28
7,2003,12,1186,75,1457,61,N,0,28,62,...,17,17,23,8,25,10,15,14,8,18
8,2003,12,1194,71,1156,66,N,0,28,58,...,18,12,27,13,26,13,25,8,2,18
9,2003,12,1458,84,1296,56,H,0,32,67,...,14,7,12,9,23,10,18,1,3,18
10,2003,13,1166,106,1426,50,H,0,41,69,...,11,12,17,8,15,8,17,7,3,15
11,2003,13,1202,74,1106,73,N,0,29,51,...,22,5,5,13,16,15,12,6,2,12
12,2003,13,1237,66,1135,65,N,0,26,66,...,19,11,17,14,21,17,18,8,4,13
13,2003,13,1323,76,1125,48,H,0,25,56,...,24,4,8,14,26,12,17,10,0,17
14,2003,14,1125,83,1135,77,N,1,30,70,...,15,17,27,20,27,17,24,7,7,19
15,2003,14,1156,78,1236,71,N,0,27,46,...,20,18,24,6,17,21,11,5,1,21
16,2003,14,1161,81,1194,56,H,0,22,48,...,13,12,19,16,18,10,16,15,3,36
17,2003,14,1166,82,1202,57,H,0,33,61,...,11,9,14,13,23,9,26,8,4,18
18,2003,14,1183,73,1129,59,A,0,29,59,...,14,14,18,12,22,10,23,4,5,14
19,2003,14,1314,85,1336,55,H,0,32,60,...,23,10,11,15,20,6,13,7,5,19
20,2003,14,1323,89,1237,45,H,0,34,62,...,15,5,11,27,22,10,17,6,3,23
21,2003,14,1353,60,1162,36,H,0,23,57,...,8,9,13,11,23,4,27,2,4,19
22,2003,14,1390,61,1131,57,H,0,20,53,...,17,16,18,11,22,7,14,7,0,24
23,2003,14,1426,59,1106,47,N,0,25,53,...,18,1,2,8,15,10,8,10,6,14
24,2003,14,1462,87,1389,48,H,0,35,70,...,20,1,4,16,18,11,19,4,3,16
25,2003,15,1161,77,1156,63,H,0,27,58,...,13,14,20,7,19,13,13,6,6,22
26,2003,15,1194,93,1236,86,N,2,33,75,...,31,18,22,9,33,20,26,6,7,25
27,2003,15,1196,76,1256,55,H,0,28,48,...,5,16,22,12,17,14,22,8,2,22
28,2003,15,1242,81,1221,57,H,0,28,53,...,21,14,21,8,22,11,20,9,3,27
29,2003,15,1422,84,1447,65,H,0,33,53,...,25,10,16,14,15,9,12,10,2,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60488,2014,130,1458,83,1278,57,N,0,30,55,...,21,11,18,10,24,9,9,3,0,22
60489,2014,131,1107,69,1392,60,A,0,23,52,...,14,14,18,12,23,9,13,5,4,20
60490,2014,131,1142,61,1169,59,N,0,23,51,...,7,18,22,17,25,6,8,3,1,18
60491,2014,131,1181,75,1301,67,N,0,28,49,...,14,11,14,13,15,13,7,4,2,19
60492,2014,131,1196,56,1397,49,N,0,21,44,...,13,9,11,8,22,7,16,7,4,18
60493,2014,131,1209,72,1117,45,N,0,26,52,...,24,6,14,10,23,10,10,0,3,19
60494,2014,131,1235,74,1124,65,N,0,24,48,...,23,11,16,9,19,12,8,8,1,18
60495,2014,131,1246,70,1208,58,N,0,26,51,...,13,21,30,3,18,6,7,8,2,16
60496,2014,131,1257,71,1163,61,N,0,25,61,...,16,9,13,9,24,14,13,3,5,20
60497,2014,131,1276,72,1326,69,N,0,25,47,...,19,8,12,9,22,17,11,10,2,18
60498,2014,131,1277,83,1458,75,N,0,29,51,...,18,24,31,9,19,13,6,2,2,18
60499,2014,131,1300,71,1288,62,N,0,19,43,...,21,13,19,12,14,12,11,5,2,26
60500,2014,131,1307,64,1361,58,N,0,18,44,...,14,13,22,15,16,5,7,11,0,23
60501,2014,131,1308,77,1225,55,N,0,29,52,...,13,17,22,4,17,8,5,5,0,17
60502,2014,131,1344,65,1166,58,N,0,19,49,...,30,8,10,7,22,14,8,3,2,18
60503,2014,131,1372,68,1358,49,N,0,25,51,...,17,10,15,5,18,11,12,1,4,20
60504,2014,131,1386,67,1382,48,N,0,21,46,...,15,16,23,12,24,8,9,7,6,22
60505,2014,131,1409,69,1256,60,N,0,23,53,...,25,15,23,10,27,7,13,3,1,22
60506,2014,131,1411,78,1341,73,N,0,22,46,...,17,11,17,13,18,13,9,8,1,29
60507,2014,131,1417,75,1112,71,N,0,25,58,...,22,6,16,8,29,16,7,7,3,15
60508,2014,131,1418,73,1443,72,N,0,29,55,...,15,15,27,8,19,12,16,6,1,17
60509,2014,131,1433,74,1203,55,N,0,26,56,...,13,10,19,7,21,13,15,7,1,15
60510,2014,131,1438,51,1338,48,N,0,21,45,...,14,9,14,9,20,9,8,6,2,14
60511,2014,131,1444,98,1405,77,N,0,34,61,...,24,13,21,12,15,12,4,6,6,18
60512,2014,131,1451,88,1315,67,H,0,30,53,...,12,18,25,15,19,7,5,4,0,15
60513,2014,132,1196,61,1246,60,N,0,23,53,...,11,21,26,12,24,9,12,4,8,19
60514,2014,132,1277,69,1276,55,N,0,27,54,...,23,15,16,13,15,7,9,3,3,15
60515,2014,132,1386,65,1433,61,N,0,24,50,...,19,8,15,13,25,9,5,6,6,18
60516,2014,132,1418,82,1209,81,N,1,32,75,...,19,20,21,4,26,8,7,5,7,15
60517,2014,132,1438,72,1181,63,N,0,21,47,...,14,7,11,14,20,13,6,7,3,29

In [44]:
for i in np.unique(dataset.season):
    print(str(i)+":"+str(dataset[raw_dataset.season == i].shape))

2003:(4616, 34)
2004:(4571, 34)
2005:(4675, 34)
2006:(4757, 34)
2007:(5043, 34)
2008:(5163, 34)
2009:(5249, 34)
2010:(5263, 34)
2011:(5246, 34)
2012:(5253, 34)
2013:(5320, 34)
2014:(5362, 34)

In [40]:
np.unique(dataset.season)

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014])

In [6]:
all_teams = pd.read_csv("../../data/teams.csv")

In [91]:
year = 2014
for index,row in all_teams.iterrows():
    teamId = all_teams.team_id[index]
    statsAsWinningTeam = (dataset[(dataset.wteam == teamId) & (dataset.season == year)])
    print(statsAsWinningTeam)
    statsAsLosingTeam = (dataset[(dataset.lteam == teamId) & (dataset.season == year)])
    print(statsAsLosingTeam)
    break

       season  daynum  wteam  wscore  lteam  lscore wloc  numot  wfgm  wfga  \
57902    2014      75   1101      73   1146      72    H      0    25    53
58812    2014      94   1101      87   1223      81    H      0    27    44

      ...   lfga3  lftm  lfta  lor  ldr  last  lto  lstl  lblk  lpf
57902 ...      10     8    20   12   23    11   16    11     1   21
58812 ...      13    16    28    9   15    18   14     6     2   28

[2 rows x 34 columns]
       season  daynum  wteam  wscore  lteam  lscore wloc  numot  wfgm  wfga  \
55266    2014       5   1182      94   1101      75    H      0    30    58
55336    2014       7   1382      75   1101      47    H      0    25    56
55426    2014       9   1268      67   1101      44    H      0    26    53
55593    2014      13   1234     103   1101      41    H      0    38    61
55693    2014      15   1395      71   1101      64    H      0    22    48
55980    2014      21   1462      93   1101      65    H      0    33    57
56224    2014      26   1406      74   1101      47    H      0    26    45
57542    2014      66   1309      87   1101      81    H      0    24    51
57677    2014      68   1368      85   1101      77    H      2    27    65
57867    2014      73   1331      82   1101      59    A      0    29    54
58183    2014      80   1249      65   1101      57    A      0    23    48
58334    2014      82   1358      70   1101      51    A      0    23    47
58531    2014      87   1372      64   1101      48    H      0    23    60
58651    2014      89   1322      84   1101      66    H      0    31    58
58998    2014      96   1394      71   1101      69    A      0    25    43
59150    2014     101   1230      80   1101      68    H      0    26    44
59813    2014     115   1311      79   1101      60    H      0    26    50
59921    2014     117   1270      95   1101      91    H      1    29    63
60238    2014     124   1230      59   1101      56    A      0    24    55

      ...   lfga3  lftm  lfta  lor  ldr  last  lto  lstl  lblk  lpf
55266 ...      25    24    32   11   22     9   10     3     1   26
55336 ...      16    15    26   11   17     7   18     2     1   30
55426 ...      21     0     0    6   17     9   16     6     0   15
55593 ...      23    10    12   10   20     6   19     3     0   21
55693 ...      20    17    25   11   26    13   13     4     2   26
55980 ...      24    10    14    3   18    11   11     3     3   24
56224 ...      19     8    11    9   14     8    7     7     3   19
57542 ...      23    18    25    7   26    20   11     7     1   32
57677 ...      19    24    35   11   34     8    7     7     0   22
57867 ...      10    16    18    8   15     5   14     3     3   17
58183 ...      14    16    23    8   22     6   22     9     2   22
58334 ...      13    15    21    7   16     7   18     6     1   24
58531 ...       9    17    23   11   20     5   21     6     5   17
58651 ...      23    14    16   12   16    11   20     8     0   18
58998 ...      20    17    22    3   16    14   16     5     0   22
59150 ...      15    16    21    6   19     9   14     6     0   19
59813 ...      17    19    25    3   26     8   12     4     1   20
59921 ...      22    20    23    4   20    17   17     4     2   25
60238 ...      19    10    11   12   20    14   20     8     2   15

[19 rows x 34 columns]

In [110]:
winningAverageStatsForTeam = statsAsWinningTeam.mean()[0:20]

In [111]:
losingAverageStatsForTeam = statsAsLosingTeam.mean()[20:]

In [112]:
stats = pd.concat([winningAverageStatsForTeam,losingAverageStatsForTeam])

In [113]:
stats

season    2014.000000
daynum      84.500000
wteam     1101.000000
wscore      80.000000
lteam     1184.500000
lscore      76.500000
numot        0.000000
wfgm        26.000000
wfga        48.500000
wfgm3        5.000000
wfga3       11.500000
wftm        23.000000
wfta        31.000000
wor          7.500000
wdr         21.500000
wast        11.500000
wto         14.500000
wstl        10.000000
wblk         2.000000
wpf         19.500000
lfgm        19.736842
lfga        50.315789
lfgm3        6.842105
lfga3       18.526316
lftm        15.052632
lfta        20.157895
lor          8.052632
ldr         20.210526
last         9.842105
lto         15.052632
lstl         5.315789
lblk         1.421053
lpf         21.789474
dtype: float64

In [141]:
cols = list(dataset.columns)

In [232]:
r = re.compile('^w')
winningStatColumnNames = filter(r.match, list(dataset.columns))
winningStatColumnNames.remove('wteam')
winningStatColumnNames.remove('wloc')
averageStatsAsWinningTeam = dataset[(dataset.wteam == teamId) & (dataset.season == year)][winningStatColumnNames].mean()
averageStatsAsWinningTeam = pd.DataFrame(averageStatsAsWinningTeam).transpose()
averageStatsAsWinningTeam

,wscore,wfgm,wfga,wfgm3,wfga3,wftm,wfta,wor,wdr,wast,wto,wstl,wblk,wpf
0,80,26,48.5,5,11.5,23,31,7.5,21.5,11.5,14.5,10,2,19.5

In [234]:
r = re.compile('^l')
losingStatColumnNames = filter(r.match, list(dataset.columns))
losingStatColumnNames.remove('lteam')
averageStatsAsLosingTeam = (dataset[(dataset.lteam == teamId) & (dataset.season == year)])[losingStatColumnNames].mean()
averageStatsAsLosingTeam = pd.DataFrame(averageStatsAsLosingTeam).transpose()
averageStatsAsLosingTeam

,lscore,lfgm,lfga,lfgm3,lfga3,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf
0,61.368421,19.736842,50.315789,6.842105,18.526316,15.052632,20.157895,8.052632,20.210526,9.842105,15.052632,5.315789,1.421053,21.789474

In [221]:
otherStatsForTargetTeam = pd.DataFrame([[teamId,year]],columns=['teamId','season'])

In [242]:
trainingStatsForTargetTeam = pd.concat([otherStatsForTargetTeam,averageStatsAsWinningTeam,averageStatsAsLosingTeam],axis=1)

In [243]:
trainingStatsForTargetTeam.columns

Index([u'teamId', u'season', u'wscore', u'wfgm', u'wfga', u'wfgm3', u'wfga3', u'wftm', u'wfta', u'wor', u'wdr', u'wast', u'wto', u'wstl', u'wblk', u'wpf', u'lscore', u'lfgm', u'lfga', u'lfgm3', u'lfga3', u'lftm', u'lfta', u'lor', u'ldr', u'last', u'lto', u'lstl', u'lblk', u'lpf'], dtype='object')

In [270]:
year = 2014
trainingStatsForAllTeams = pd.DataFrame()
for index,row in all_teams.iterrows():
    teamId = all_teams.team_id[index]

    # Stats for target team as winning team
    r = re.compile('^w')
    winningStatColumnNames = filter(r.match, list(dataset.columns))
    winningStatColumnNames.remove('wteam')
    winningStatColumnNames.remove('wloc')
    averageStatsAsWinningTeam = dataset[(dataset.wteam == teamId) & (dataset.season == year)][winningStatColumnNames].mean()
    averageStatsAsWinningTeam = pd.DataFrame(averageStatsAsWinningTeam).transpose()
    averageStatsAsWinningTeam

    # Stats for target team as losing team
        # Potential change here is to include Average Stats of the teams that lose to this team.
    r = re.compile('^l')
    losingStatColumnNames = filter(r.match, list(dataset.columns))
    losingStatColumnNames.remove('lteam')
    averageStatsAsLosingTeam = (dataset[(dataset.lteam == teamId) & (dataset.season == year)])[losingStatColumnNames].mean()
    averageStatsAsLosingTeam = pd.DataFrame(averageStatsAsLosingTeam).transpose()
    averageStatsAsLosingTeam

    # Meta data
    otherStatsForTargetTeam = pd.DataFrame([[teamId,year]],columns=['teamId','season'])

    trainingStatsForTargetTeam = pd.concat([otherStatsForTargetTeam,averageStatsAsWinningTeam,averageStatsAsLosingTeam],axis=1)
    
    trainingStatsForAllTeams = trainingStatsForAllTeams.append(trainingStatsForTargetTeam,ignore_index=True)

In [268]:
trainingStatsForAllTeams.to_csv("../../data/structured/trainingStatsForAllTeams.csv")

In [271]:
pd.DataFrame(trainingStatsForAllTeams)

,teamId,season,wscore,wfgm,wfga,wfgm3,wfga3,wftm,wfta,wor,...,lfga3,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf
0,1101,2014,80.000000,26.000000,48.500000,5.000000,11.500000,23.000000,31.000000,7.500000,...,18.526316,15.052632,20.157895,8.052632,20.210526,9.842105,15.052632,5.315789,1.421053,21.789474
1,1102,2014,69.700000,22.300000,50.200000,7.900000,21.000000,17.200000,23.400000,9.600000,...,22.111111,11.111111,16.944444,8.222222,21.333333,13.222222,13.055556,4.833333,2.722222,19.888889
2,1103,2014,71.809524,24.666667,54.285714,7.571429,20.095238,14.904762,24.047619,11.809524,...,20.916667,11.666667,19.000000,13.166667,19.500000,8.916667,14.000000,5.666667,3.166667,18.416667
3,1104,2014,73.583333,25.333333,51.333333,7.083333,17.916667,15.833333,23.666667,9.916667,...,16.842105,15.368421,22.210526,9.894737,21.473684,9.526316,11.684211,5.684211,4.000000,20.947368
4,1105,2014,71.166667,23.833333,52.083333,6.583333,17.416667,16.916667,25.833333,11.333333,...,20.000000,12.937500,19.250000,8.687500,21.562500,11.250000,13.312500,5.687500,3.562500,22.812500
5,1106,2014,74.750000,25.625000,58.437500,5.875000,19.250000,17.625000,24.687500,13.562500,...,18.250000,14.500000,22.666667,12.250000,19.166667,10.333333,11.500000,6.500000,3.416667,18.833333
6,1107,2014,72.166667,23.277778,50.055556,6.222222,14.333333,19.388889,25.222222,10.555556,...,12.357143,12.214286,17.214286,10.071429,22.857143,10.071429,12.142857,3.928571,2.642857,17.428571
7,1108,2014,65.111111,22.333333,45.888889,4.555556,12.000000,15.888889,23.222222,6.555556,...,16.000000,13.631579,21.105263,11.052632,19.263158,8.210526,11.842105,5.894737,4.000000,20.315789
8,1109,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1110,2014,67.500000,23.850000,46.200000,6.150000,15.450000,13.650000,18.900000,7.250000,...,18.500000,8.000000,11.833333,6.916667,19.083333,12.916667,14.000000,5.416667,3.250000,18.916667
10,1111,2014,70.400000,24.800000,53.400000,6.000000,14.600000,14.800000,24.200000,10.600000,...,16.142857,14.619048,22.761905,13.333333,20.904762,8.809524,12.809524,6.095238,2.380952,21.000000
11,1112,2014,74.400000,26.633333,55.500000,5.433333,14.833333,15.700000,23.766667,12.633333,...,15.000000,12.250000,20.250000,12.250000,29.500000,11.500000,11.500000,6.500000,3.000000,16.250000
12,1113,2014,80.095238,27.476190,56.190476,8.285714,19.952381,16.857143,24.047619,8.190476,...,23.090909,15.363636,22.636364,8.909091,22.454545,10.636364,12.363636,4.636364,3.818182,21.000000
13,1114,2014,73.538462,25.230769,54.307692,4.692308,12.461538,18.384615,24.538462,10.615385,...,17.882353,17.058824,23.176471,11.941176,24.411765,10.470588,13.705882,5.411765,3.529412,23.117647
14,1115,2014,70.545455,23.090909,49.818182,6.272727,17.181818,18.090909,27.545455,9.181818,...,18.833333,11.500000,17.611111,10.666667,18.166667,11.722222,15.166667,8.944444,2.388889,20.000000
15,1116,2014,84.904762,29.095238,60.904762,7.857143,19.952381,18.857143,26.000000,11.000000,...,21.636364,17.181818,23.727273,13.090909,20.363636,12.000000,11.181818,7.181818,4.727273,23.272727
16,1117,2014,81.235294,25.705882,55.529412,9.411765,22.647059,20.411765,27.764706,9.764706,...,23.615385,12.923077,18.615385,8.846154,22.461538,12.153846,13.384615,5.538462,2.153846,18.692308
17,1118,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1119,2014,76.857143,27.214286,55.857143,7.714286,19.571429,14.714286,20.428571,9.785714,...,24.687500,11.875000,17.562500,12.562500,20.062500,13.062500,13.062500,5.625000,4.187500,19.062500
19,1120,2014,78.071429,25.642857,52.071429,5.214286,16.214286,21.571429,29.285714,10.642857,...,20.437500,14.000000,20.000000,11.312500,21.250000,9.937500,12.250000,5.437500,4.187500,22.812500
20,1121,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1122,2014,81.000000,27.100000,51.100000,5.600000,13.600000,21.200000,31.600000,8.200000,...,15.833333,16.388889,24.222222,10.777778,21.833333,13.333333,17.055556,6.833333,4.500000,17.611111
22,1123,2014,77.333333,26.000000,57.666667,7.333333,22.000000,18.000000,25.333333,13.333333,...,20.240000,14.960000,22.000000,11.960000,23.240000,11.640000,17.560000,4.440000,2.280000,21.120000
23,1124,2014,77.727273,26.090909,55.227273,7.136364,18.136364,18.409091,26.363636,14.636364,...,21.454545,12.363636,20.363636,13.272727,20.909091,12.909091,12.090909,4.818182,4.181818,19.818182
24,1125,2014,83.304348,28.260870,53.739130,8.869565,21.347826,17.913043,24.217391,7.826087,...,24.666667,13.888889,19.444444,9.000000,21.555556,14.555556,16.555556,5.111111,2.666667,23.444444
25,1126,2014,72.000000,23.800000,49.800000,8.400000,17.600000,16.000000,22.200000,8.000000,...,19.280000,12.280000,17.280000,11.720000,18.240000,8.640000,12.320000,5.720000,2.520000,21.480000
26,1127,2014,73.428571,24.142857,55.285714,8.142857,18.857143,17.000000,23.714286,11.428571,...,19.000000,15.521739,22.652174,10.086957,20.608696,8.608696,14.521739,5.652174,1.826087,20.391304
27,1128,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1129,2014,81.368421,27.263158,56.736842,8.263158,20.631579,18.578947,23.894737,10.368421,...,20.538462,11.846154,16.615385,11.461538,20.692308,9.384615,10.461538,4.846154,2.076923,19.923077
29,1130,2014,75.142857,24.000000,52.285714,9.285714,24.571429,17.857143,22.571429,9.428571,...,21.166667,16.166667,22.166667,7.916667,19.666667,11.708333,11.291667,4.458333,2.500000,19.458333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,1435,2014,69.733333,23.266667,50.866667,6.800000,19.466667,16.400000,25.466667,9.533333,...,19.187500,11.687500,17.250000,10.125000,22.750000,11.625000,14.687500,4.625000,4.125000,18.562500
335,1436,2014,73.550000,24.300000,49.600000,5.900000,13.500000,19.050000,24.950000,10.300000,...,17.200000,13.600000,21.300000,10.000000,20.300000,11.100000,10.100000,5.400000,3.400000,21.900000
336,1437,2014,80.000000,26.321429,56.357143,9.071429,25.000000,18.285714,25.678571,11.535714,...,25.250000,16.000000,22.250000,9.500000,20.750000,11.250000,10.750000,5.000000,2.250000,19.500000
337,1438,2014,67.500000,23.964286,50.964286,6.000000,15.500000,13.571429,20.892857,10.821429,...,13.166667,17.833333,24.833333,11.333333,22.500000,8.833333,11.833333,3.833333,4.666667,19.500000
338,1439,2014,78.111111,26.444444,56.666667,8.444444,19.777778,16.777778,23.555556,10.444444,...,19.000000,11.545455,18.772727,11.000000,23.454545,9.727273,12.772727,3.409091,3.772727,16.227273
339,1440,2014,91.066667,32.333333,69.800000,9.200000,26.066667,17.200000,25.133333,15.000000,...,28.333333,14.000000,19.916667,12.750000,24.083333,10.333333,10.000000,6.083333,5.583333,19.416667
340,1441,2014,78.062500,26.687500,58.875000,7.375000,18.750000,17.312500,23.375000,12.875000,...,21.466667,13.933333,20.266667,13.533333,19.666667,9.800000,12.000000,6.466667,4.066667,24.066667
341,1442,2014,69.571429,24.714286,49.142857,4.285714,11.142857,15.857143,20.857143,7.571429,...,15.350000,11.500000,17.750000,7.450000,20.500000,10.550000,13.300000,5.350000,2.450000,20.450000
342,1443,2014,69.684211,23.315789,53.578947,6.631579,19.789474,16.421053,24.052632,11.578947,...,25.166667,12.833333,21.583333,14.083333,23.500000,11.250000,14.583333,4.250000,1.916667,21.250000
343,1444,2014,76.500000,24.909091,50.500000,6.045455,16.727273,20.636364,28.136364,9.681818,...,20.444444,14.555556,21.777778,9.555556,22.333333,10.222222,15.222222,6.555556,4.111111,20.555556
344,1445,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,1446,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,1447,2014,73.666667,25.277778,57.333333,6.333333,16.555556,16.777778,22.944444,13.000000,...,16.250000,14.833333,20.000000,12.916667,23.000000,10.500000,12.166667,5.500000,4.750000,22.250000
347,1448,2014,76.764706,26.352941,54.823529,5.235294,15.117647,18.823529,28.705882,11.117647,...,15.437500,15.375000,23.937500,9.187500,19.687500,11.625000,12.687500,5.437500,3.187500,20.875000
348,1449,2014,79.882353,27.176471,56.705882,5.882353,16.764706,19.647059,25.411765,10.764706,...,17.800000,12.866667,17.533333,11.400000,21.066667,12.333333,11.200000,4.933333,2.333333,20.600000
349,1450,2014,71.000000,24.000000,55.000000,6.666667,21.555556,16.333333,26.111111,12.666667,...,23.095238,11.285714,16.619048,8.333333,20.857143,9.809524,11.428571,4.285714,2.476190,18.714286
350,1451,2014,76.235294,24.294118,47.705882,8.411765,18.647059,19.235294,25.705882,7.705882,...,17.818182,16.363636,22.727273,9.000000,22.181818,9.636364,11.909091,3.636364,4.181818,18.363636
351,1452,2014,85.588235,29.294118,59.529412,8.823529,20.411765,18.176471,24.588235,11.882353,...,20.666667,15.466667,21.933333,12.200000,22.066667,10.466667,9.866667,5.933333,2.466667,21.666667
352,1453,2014,76.571429,26.714286,54.904762,4.809524,12.952381,18.333333,25.190476,11.190476,...,15.166667,13.166667,18.666667,11.666667,22.666667,11.666667,14.500000,6.000000,6.500000,20.666667
353,1454,2014,75.400000,24.000000,52.000000,7.950000,21.150000,19.450000,26.050000,9.950000,...,22.307692,15.000000,21.230769,9.538462,20.923077,11.923077,14.153846,5.307692,2.692308,17.769231
354,1455,2014,74.939394,24.727273,54.090909,6.848485,19.727273,18.636364,25.575758,11.878788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,1456,2014,77.473684,26.105263,50.210526,9.315789,20.368421,15.947368,22.210526,7.000000,...,23.416667,11.916667,18.666667,8.416667,21.833333,13.166667,10.916667,5.166667,2.666667,17.416667
356,1457,2014,77.294118,25.705882,54.529412,8.235294,19.588235,17.647059,24.235294,9.941176,...,21.538462,14.153846,20.230769,9.923077,19.769231,10.384615,14.000000,4.692308,2.538462,21.923077
357,1458,2014,75.384615,24.615385,52.576923,8.192308,21.000000,17.961538,23.884615,8.692308,...,20.000000,15.142857,21.285714,9.142857,20.857143,10.857143,8.285714,4.000000,3.285714,16.000000
358,1459,2014,70.529412,25.823529,54.235294,6.411765,15.823529,12.470588,19.470588,10.588235,...,16.166667,11.750000,16.666667,10.500000,18.833333,10.666667,11.750000,5.333333,1.166667,18.416667
359,1460,2014,67.666667,21.388889,46.888889,6.000000,15.777778,18.888889,24.777778,7.055556,...,18.428571,12.214286,17.714286,7.142857,20.357143,13.785714,13.714286,7.000000,2.500000,22.214286
360,1461,2014,69.750000,22.312500,43.625000,5.875000,14.750000,19.250000,26.250000,4.437500,...,17.285714,10.928571,15.857143,5.857143,20.500000,10.428571,9.214286,4.428571,3.142857,17.714286
361,1462,2014,74.714286,26.238095,53.142857,5.190476,12.809524,17.047619,24.476190,10.714286,...,18.083333,13.416667,20.000000,11.916667,21.333333,12.833333,13.083333,4.583333,1.916667,21.916667
362,1463,2014,72.071429,22.214286,50.071429,5.500000,14.928571,22.142857,31.142857,12.571429,...,16.384615,16.384615,24.230769,11.076923,20.769231,9.230769,12.384615,6.230769,3.846154,20.461538
363,1464,2014,74.666667,25.333333,53.500000,7.750000,21.333333,16.250000,22.666667,7.916667,...,22.235294,16.470588,22.117647,8.647059,22.352941,14.529412,11.764706,6.588235,2.176471,20.294118

In [275]:
all_teams.shape[0]

364

In [306]:
ROOT_DIR = "../../"

season_statistics = pd.read_csv(ROOT_DIR+"data/raw/regular_season_detailed_results.csv");
tournament_statistics = pd.read_csv(ROOT_DIR+"data/raw/tourney_detailed_results.csv")
team_statistics = pd.read_csv(ROOT_DIR+"data/structured/average_team_stats_for_all_teams.csv");
all_teams = pd.read_csv(ROOT_DIR+"data/raw/teams.csv")

all_tournament_seasons = np.unique(tournament_statistics.season)

# Drop the first index column
team_statistics = team_statistics.drop(team_statistics.columns[0],axis=1)
 
team_statistics.drop(team_statistics.columns[0],axis=1);

for season in all_tournament_seasons:
    #Select that part of the tournament
    tournament_statistics_for_season = tournament_statistics[tournament_statistics.season == season]
    #Find the two teams
    #Get their stats_vector from team_stats
    #Find difference between the vectors
    #sort the teamIds
    #Take the difference vector and append it with the label it with 0 if first team won, and 1 if the second team won

In [360]:
training_data = pd.DataFrame()

for season in all_tournament_seasons:
    tournament_statistics_for_season = tournament_statistics[tournament_statistics.season == season]
    team_statistics_for_season = team_statistics[team_statistics.season == season]
    for index,row in tournament_statistics_for_season.iterrows():
        tournament_match = row

        #Find the two teams
        winning_team_id = tournament_match['wteam']
        losing_team_id =  tournament_match['lteam']

        #Here, we enforce a convention for labeling: 
        #if: win_team_id  < lose_team_id 
            #(1101) < (1102)
            #then: output label: 0 -> 1101 won
        #else: 
            #(1102) > (1101)    
            #then: output label: 1 -> 1102 won

        #Get their stats_vector from team_stats
        if(winning_team_id < losing_team_id):
            team1_statistic = team_statistics_for_season[team_statistics_for_season.teamId == winning_team_id]
            team2_statistic = team_statistics_for_season[team_statistics_for_season.teamId == losing_team_id]
            output_label = 0
        else:
            team1_statistic = team_statistics_for_season[team_statistics_for_season.teamId == losing_team_id]
            team2_statistic = team_statistics_for_season[team_statistics_for_season.teamId == winning_team_id]
            output_label = 1

        team1_np_vector = team1_statistic[team1_statistic.columns[2:]].as_matrix()
        team2_np_vector = team2_statistic[team2_statistic.columns[2:]].as_matrix()

        #Find difference between the vectors
        match_vector = team1_np_vector - team2_np_vector


        #Take the difference vector and append it with the label it with 0 if first team won, and 1 if the second team won
        match_statistics = pd.DataFrame(match_vector,columns=team1_statistic.columns[2:])
        match_output_label = pd.DataFrame([output_label],columns=["winningTeam"])

        row_vector_for_training_data = pd.concat([match_statistics,match_output_label],axis=1)

        # Append to training-data-for-season
        training_data = training_data.append(row_vector_for_training_data,ignore_index=True)

In [361]:
training_data

,wscore,wfgm,wfga,wfgm3,wfga3,wftm,wfta,wor,wdr,wast,...,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf,winningTeam
0,-2.205128,-1.619658,-3.957265,-0.923077,0.269231,1.957265,7.940171,-0.307692,1.170940,-1.141026,...,-0.854167,4.083333,2.666667,0.104167,2.375000,-3.666667,1.437500,-0.062500,-2.250000,1
1,14.410526,4.482105,9.629474,1.764211,4.818947,3.682105,4.490526,1.734737,1.054737,2.515789,...,4.600000,5.466667,5.300000,0.233333,1.600000,-0.533333,2.166667,1.300000,2.900000,0
2,5.896135,2.403382,-3.490338,-3.661836,-8.900966,4.751208,6.198068,0.217391,-1.429952,-0.664251,...,-2.409091,-3.575758,-1.984848,-3.151515,0.439394,1.515152,-2.303030,-2.712121,-1.333333,0
3,2.658171,-1.250375,-4.796102,-0.851574,-2.830585,6.010495,5.301349,-0.506747,0.197901,-0.847076,...,4.166667,6.666667,0.000000,1.666667,0.083333,4.666667,0.166667,0.666667,5.916667,0
4,-1.793651,1.904762,4.468254,-2.896825,-6.738095,-2.706349,-1.436508,1.253968,2.404762,0.000000,...,-3.625000,-2.208333,2.750000,0.541667,2.583333,-1.250000,-0.916667,0.291667,-1.875000,0
5,-11.146998,-6.538302,-13.219462,-0.236025,0.184265,2.165631,0.614907,-5.020704,-4.523810,-2.881988,...,5.888889,5.500000,-0.916667,-1.361111,-1.111111,-0.958333,1.361111,-3.486111,4.361111,1
6,-4.647059,-0.522059,-7.289216,-3.291667,-8.938725,-0.311275,-0.259804,-2.198529,1.698529,2.894608,...,-3.435897,-5.692308,-5.025641,1.384615,1.743590,3.153846,-2.051282,0.935897,-3.948718,1
7,-5.948849,-2.122762,1.416880,-0.393862,0.657289,-1.309463,-0.895141,-0.127877,-1.158568,-2.483376,...,-5.159091,-5.886364,1.215909,-1.931818,-4.443182,-3.511364,-1.443182,0.090909,1.090909,1
8,3.382246,2.556159,1.568841,0.625000,0.920290,-2.355072,-4.936594,-2.222826,1.070652,5.291667,...,5.708333,5.958333,-3.458333,5.250000,-0.583333,-3.166667,-0.708333,0.583333,5.208333,0
9,16.658103,7.494071,10.037549,0.411067,1.284585,1.258893,3.438735,1.415020,4.523715,2.950593,...,2.160714,5.053571,2.589286,4.250000,1.785714,1.142857,0.982143,2.339286,1.321429,0
10,-8.220870,-2.551304,-2.513043,-0.248696,-0.532174,-2.869565,-2.316522,-0.886957,0.575652,-0.732174,...,-1.750000,1.600000,-1.950000,-2.250000,-2.550000,-0.050000,4.700000,0.850000,-2.450000,1
11,-0.660714,-0.404762,2.500000,1.857143,6.089286,-1.708333,-0.880952,3.482143,4.529762,1.702381,...,0.133333,-0.533333,-0.600000,1.600000,-3.000000,-0.833333,-1.633333,-0.733333,-4.933333,0
12,3.555336,0.337945,3.545455,0.490119,-0.349802,2.389328,0.181818,-0.883399,5.478261,-0.106719,...,3.603175,5.714286,1.682540,0.380952,0.047619,-0.857143,-1.936508,-0.396825,-3.301587,0
13,-2.033333,0.275000,3.358333,2.600000,4.175000,-5.183333,-6.925000,-0.266667,-0.066667,4.125000,...,-5.233333,-8.800000,-1.366667,1.000000,1.033333,-8.700000,-2.066667,1.500000,-3.666667,0
14,4.506394,0.184143,-4.181586,-0.450128,-2.398977,4.588235,6.567775,-1.547315,1.746803,1.772379,...,1.238636,3.750000,-4.500000,1.295455,2.875000,4.454545,1.659091,0.761364,1.772727,1
15,-1.113636,-2.246212,-3.234848,0.931818,3.454545,2.446970,3.617424,2.681818,-3.439394,0.079545,...,-1.355556,-0.444444,1.400000,-2.222222,0.311111,-4.422222,-1.400000,-1.511111,1.022222,1
16,2.072727,-1.080000,-0.705455,-0.163636,1.381818,4.396364,6.965455,-0.425455,-0.238182,0.712727,...,1.821429,0.142857,2.178571,0.607143,1.250000,3.321429,0.035714,-0.678571,0.857143,1
17,3.546911,2.899314,0.867277,-2.828375,-7.276888,0.576659,2.009153,1.123570,0.791762,0.508009,...,-2.484848,-5.166667,-0.045455,-5.393939,-0.590909,4.136364,0.287879,-1.954545,-5.136364,0
18,-4.041667,-3.327381,-5.678571,3.125000,6.738095,-0.511905,-2.345238,-5.041667,-5.630952,-1.797619,...,-0.222222,0.555556,-3.866667,-1.844444,-2.444444,-0.622222,-0.044444,-0.888889,4.333333,0
19,6.601190,3.630952,5.458333,3.261905,6.422619,-3.922619,-5.226190,0.357143,-1.500000,0.744048,...,-1.285714,-2.261905,-1.095238,-2.380952,1.190476,-4.761905,-0.595238,-1.880952,-5.833333,0
20,-0.744118,1.073529,1.852941,-1.091176,-1.126471,-1.800000,-2.220588,1.679412,-1.738235,-1.200000,...,-0.242424,-0.628788,3.469697,-1.325758,-2.318182,0.969697,2.136364,-0.818182,0.454545,1
21,-3.491833,-2.967332,-5.226860,0.932849,2.814882,1.509982,1.566243,-2.072595,-2.956443,-0.816697,...,3.846154,6.307692,0.000000,-1.000000,-3.589744,5.179487,1.666667,-1.717949,4.358974,1
22,-11.341667,-4.558333,-10.608333,-3.100000,-7.825000,0.875000,2.016667,-2.683333,-0.433333,-3.008333,...,-6.261905,-11.166667,-2.380952,-1.595238,-3.309524,2.238095,1.619048,-0.642857,-7.904762,1
23,10.451754,3.491228,4.510965,0.252193,-1.537281,3.217105,3.934211,3.015351,3.453947,5.179825,...,3.500000,5.111111,6.333333,5.833333,3.000000,0.000000,-0.055556,4.333333,-0.611111,0
24,10.665789,4.636842,9.600000,1.128947,3.676316,0.263158,2.073684,3.944737,4.215789,1.344737,...,-1.098485,0.992424,3.689394,2.689394,-3.196970,-1.787879,0.901515,2.537879,-3.295455,1
25,0.763636,1.390909,4.159091,-4.195455,-8.363636,2.177273,5.240909,3.418182,-0.454545,-2.509091,...,-0.244444,0.133333,1.888889,2.311111,-0.533333,-0.333333,-0.311111,3.222222,-0.044444,0
26,-0.664835,0.214286,-1.234432,-0.565934,0.543956,-0.527473,2.771062,0.613553,2.168498,2.089744,...,1.950000,4.350000,-4.000000,3.350000,-2.100000,-1.250000,1.900000,1.000000,0.500000,0
27,-0.341270,2.404762,-0.936508,1.396825,0.904762,-6.547619,-5.793651,0.539683,0.507937,4.293651,...,-6.200000,-5.800000,-0.400000,1.600000,3.200000,-0.500000,1.000000,2.100000,-1.700000,1
28,-5.668478,-4.454710,-5.353261,-0.141304,-0.789855,3.382246,1.554348,-1.985507,-3.447464,-2.244565,...,-0.900000,-4.500000,-7.833333,-3.333333,4.633333,0.333333,2.200000,-4.600000,7.633333,1
29,-1.311189,0.723776,3.335664,-1.423077,-0.958042,-1.335664,0.066434,3.919580,0.251748,-1.716783,...,3.479167,5.416667,3.750000,3.770833,3.791667,-4.750000,-1.479167,1.437500,5.666667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,6.985507,2.053140,0.640902,1.436393,1.974235,1.442834,2.694042,-1.217391,1.951691,1.579710,...,-1.000000,-0.600000,-2.900000,1.300000,1.300000,6.900000,-1.200000,-2.100000,2.900000,0
751,-6.460000,-2.548750,-2.720000,1.911250,4.902500,-3.273750,-2.390000,-0.485000,-1.066250,-3.321250,...,-4.166667,-5.444444,-3.055556,1.944444,-4.166667,3.722222,1.888889,-1.611111,-1.111111,0
752,12.441379,4.746207,6.067586,2.430345,3.710345,0.518621,2.620690,4.004138,-1.543448,1.968276,...,-0.633333,0.166667,2.766667,-2.833333,-1.300000,0.100000,0.000000,0.900000,4.600000,0
753,1.742609,0.622609,-4.360000,4.193043,7.340870,-3.695652,-8.471304,-5.834783,-4.885217,2.806957,...,-0.750000,-3.925000,-6.875000,-1.775000,-2.900000,-1.600000,-1.650000,-3.175000,-3.950000,0
754,-4.704615,-3.369231,-6.860000,-2.587692,-6.070769,4.621538,5.269231,-1.269231,-2.595385,-3.073846,...,3.250000,5.500000,2.375000,-3.375000,-2.500000,-2.625000,2.875000,1.125000,1.250000,1
755,6.451178,3.235690,-2.247475,0.284512,-0.053872,-0.304714,-3.786195,-3.563973,-0.434343,2.210438,...,3.833333,3.333333,-5.666667,-0.083333,3.666667,2.166667,-3.000000,1.166667,5.083333,1
756,9.354515,3.558528,4.988294,-0.061873,-1.695652,2.299331,2.984950,1.698997,-0.346154,2.625418,...,1.523810,-0.619048,2.634921,-1.190476,1.920635,3.936508,2.888889,-0.730159,7.444444,1
757,-3.488889,-0.440741,0.981481,-1.937037,-3.092593,-0.670370,0.951852,2.855556,-1.244444,0.937037,...,-0.250000,1.583333,3.250000,7.166667,-2.333333,-0.833333,0.833333,-0.666667,-6.583333,0
758,-5.695804,-2.447552,0.419580,-3.825175,-5.940559,3.024476,6.017483,6.405594,-1.094406,-3.643357,...,2.506494,6.792208,3.987013,-1.948052,-0.233766,1.519481,1.389610,2.753247,0.532468,0
759,5.453177,1.593645,2.046823,4.113712,11.068562,-1.847826,-4.389632,-4.503344,3.478261,2.876254,...,1.841270,-2.222222,-1.000000,-0.269841,2.015873,1.000000,-0.873016,-1.603175,-2.301587,0
760,3.518939,1.439394,1.617424,-1.765152,-3.435606,2.405303,4.715909,2.662879,0.689394,-1.321970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
761,5.851190,2.148810,0.839286,-0.684524,-0.065476,2.238095,2.523810,1.833333,0.666667,3.505952,...,1.388889,2.388889,3.194444,1.083333,1.500000,2.416667,2.138889,1.833333,2.777778,1
762,1.919565,0.810870,0.676087,2.419565,5.210870,-2.121739,-2.980435,-2.441304,0.019565,3.336957,...,2.458333,1.500000,-2.833333,-0.625000,2.916667,0.208333,2.625000,-1.791667,4.166667,1
763,-8.645889,-4.132626,-2.164456,0.714854,4.984085,-1.095491,-0.351459,3.072944,-5.488064,-1.810345,...,-7.875000,-6.625000,2.000000,-6.375000,-0.500000,1.000000,-4.000000,0.125000,-0.250000,1
764,11.727273,4.944805,7.262987,-0.545455,-0.227273,2.383117,3.925325,1.860390,0.847403,3.863636,...,-3.833333,-4.277778,1.333333,-0.833333,6.055556,1.611111,3.388889,-0.111111,1.055556,1
765,4.214815,2.596296,0.388889,0.581481,0.870370,-1.559259,-1.974074,0.114815,0.977778,5.640741,...,0.750000,1.250000,-3.250000,12.250000,6.000000,2.000000,-2.000000,1.000000,-1.000000,0
766,-0.538302,0.132505,1.207039,0.219462,0.968944,-1.022774,-1.041408,2.449275,-2.492754,0.627329,...,-3.233333,-3.366667,1.050000,-0.083333,1.933333,1.250000,1.450000,-1.200000,-2.033333,0
767,-14.076923,-6.084135,-5.923077,0.608173,3.908654,-2.516827,-0.480769,1.913462,-2.290865,-4.781250,...,-4.875000,-4.125000,-2.000000,-0.375000,-5.500000,1.500000,-2.000000,-0.375000,-5.250000,0
768,2.342657,1.475524,2.650350,-1.055944,-2.863636,0.447552,2.479021,5.944056,0.290210,2.856643,...,-2.779221,-0.922078,4.129870,0.051948,2.051948,3.805195,0.818182,0.896104,3.818182,1
769,-9.423077,-4.153846,-6.692308,-0.846154,-5.038462,-0.269231,-2.346154,0.769231,-4.000000,-6.192308,...,0.839286,-1.000000,-3.500000,-0.285714,-4.696429,-1.000000,-1.196429,3.214286,1.482143,0
770,-5.783046,-3.419540,-5.119253,-3.227011,-5.018678,4.283046,4.670977,0.817529,2.520115,-4.406609,...,5.900000,10.300000,1.300000,4.300000,-1.000000,0.400000,-2.800000,0.600000,-0.600000,0
771,1.010000,0.390000,-1.510000,2.830000,6.030000,-2.600000,-3.930000,-4.450000,-3.170000,1.970000,...,0.083333,-3.625000,-5.208333,-1.375000,0.166667,-1.416667,0.000000,-2.041667,-3.583333,0
772,12.884615,4.804945,7.535714,2.307692,4.730769,0.967033,-0.162088,0.447802,2.008242,4.153846,...,-8.333333,-10.333333,-0.958333,-0.125000,4.416667,0.791667,1.041667,-1.041667,0.000000,0
773,5.152174,2.077446,1.826087,-0.335598,-2.236413,1.332880,1.184783,-0.092391,0.080163,0.194293,...,2.100000,1.800000,2.800000,0.000000,3.600000,0.000000,-1.800000,0.800000,3.300000,1
774,-0.984615,2.017949,2.923077,-2.758974,-6.166667,-2.261538,-0.117949,3.941026,0.520513,3.105128,...,-2.892857,-1.035714,3.107143,8.642857,0.642857,3.214286,2.500000,-0.285714,0.250000,1
775,-4.615385,-2.807692,-3.884615,-0.692308,-2.461538,1.692308,0.576923,-1.307692,-1.115385,-4.730769,...,5.625000,5.500000,0.125000,0.625000,-3.375000,-0.625000,0.500000,1.875000,1.125000,0
776,0.498333,-0.673333,2.068333,-4.196667,-5.788333,6.041667,10.371667,5.941667,3.736667,-3.678333,...,5.350000,11.925000,5.275000,3.675000,0.700000,3.000000,-0.050000,2.875000,5.750000,0
777,4.269231,1.430288,1.615385,0.584135,-1.293269,0.824519,-1.942308,-1.913462,1.906250,-0.295673,...,4.625000,3.000000,2.000000,0.500000,2.375000,-1.500000,-1.625000,4.000000,4.625000,0
778,3.073718,1.551282,3.131410,-3.108974,-4.708333,3.080128,6.407051,5.849359,2.070513,-0.419872,...,3.957143,8.014286,5.757143,3.442857,-0.657143,5.714286,0.200000,1.714286,6.000000,0
779,-2.689103,-0.205128,-1.092949,2.532051,1.477564,-4.810897,-8.983974,-4.580128,-1.416667,1.381410,...,-3.975000,-9.300000,-4.400000,-1.300000,-0.325000,-2.000000,1.175000,0.500000,-1.375000,0

In [350]:
row_vector_for_training_data

,wscore,wfgm,wfga,wfgm3,wfga3,wftm,wfta,wor,wdr,wast,...,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf,winningTeam
0,-10.083333,-4.472222,-7.256944,-2.527778,-7.479167,1.388889,1.659722,0.243056,1.340278,-0.291667,...,-1.910714,-2.598214,0.258929,2.544643,-1.303571,-0.169643,-3.258929,-0.482143,-3.008929,0

In [3]:
import pandas as pd
import numpy as np
import re

# 
# Creates MATCH statistics for all tournament matches in a season (for all seasons)
# 

ROOT_DIR = "../../"

season_data_file_path = "data/raw/regular_season_detailed_results.csv"
team_statistic_file_path = "data/structured/average_team_stats_for_all_teams.csv"
season_tournament_file_path = "data/raw/tourney_detailed_results.csv"
training_data_match_stats_file_path = "data/structured/training_data_match_statistics.csv"
season_statistics = pd.read_csv(ROOT_DIR+season_data_file_path);
tournament_statistics = pd.read_csv(ROOT_DIR+season_tournament_file_path);
team_statistics = pd.read_csv(ROOT_DIR+team_statistic_file_path);
all_teams = pd.read_csv(ROOT_DIR+"data/raw/teams.csv")

all_tournament_seasons = np.unique(tournament_statistics.season)
training_data = pd.DataFrame()

for season in all_tournament_seasons:
    print("Processing Data for :"+str(season))
    tournament_statistics_for_season = tournament_statistics[tournament_statistics.season == season]
    team_statistics_for_season = team_statistics[team_statistics.season == season]
    for index,row in tournament_statistics_for_season.iterrows():
        tournament_match = row

        #Find the two teams
        winning_team_id = tournament_match['wteam']
        losing_team_id =  tournament_match['lteam']

        #Here, we enforce a convention for labeling: 
        #Get their stats_vector from team_stats
        if(winning_team_id < losing_team_id):
            team1_statistic = team_statistics_for_season[team_statistics_for_season.teamId == winning_team_id]
            team2_statistic = team_statistics_for_season[team_statistics_for_season.teamId == losing_team_id]
            output_label = 0
        else:
            team1_statistic = team_statistics_for_season[team_statistics_for_season.teamId == losing_team_id]
            team2_statistic = team_statistics_for_season[team_statistics_for_season.teamId == winning_team_id]
            output_label = 1

        team1_np_vector = team1_statistic[team1_statistic.columns[2:]].as_matrix()
        team2_np_vector = team2_statistic[team2_statistic.columns[2:]].as_matrix()

        #Find difference between the vectors
        match_vector = team1_np_vector - team2_np_vector

        #Take the difference vector and append it with the label it with 0 if first team won, and 1 if the second team won
        match_team_ids = pd.DataFrame([winning_team_id,losing_team_id],columns=["wTeamId","lTeamId"])
        match_statistics = pd.DataFrame(match_vector,columns=team1_statistic.columns[2:])
        match_output_label = pd.DataFrame([output_label],columns=["winningTeam"])

        row_vector_for_training_data = pd.concat([match_team_ids,match_statistics,match_output_label],axis=1)
        row_vector_for_training_data.season = season

        # Append to training-data-for-season
        training_data = training_data.append(row_vector_for_training_data,ignore_index=True)
        break
    break
training_data

In [2]:
training_data

NameError: name 'training_data' is not defined